name: akinator-clone
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - expat=2.7.1
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - ncurses=6.4
  - openssl=3.0.17
  - pip=25.1
  - pthread-stubs=0.3
  - python=3.10.18
  - readline=8.2
  - setuptools=78.1.1
  - sqlite=3.50.2
  - tk=8.6.14
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - country-converter==1.3.1
      - joblib==1.5.1
      - numpy==2.2.6
      - pandas==2.3.1
      - pytz==2025.2
      - scikit-learn==1.7.1
      - scipy==1.15.3
      - threadpoolctl==3.6.0
      - tzdata==2025.2
